# Architecture
arch: mobilenetv2

# ===== Dataset ===== #
data: /path/to/ImageNet
set: ImageNet
name: Mask

# ===== Learning Rate Policy ======== #
optimizer: sgd
lr: 0.05
lr_policy: cosine_lr
warmup_length: 1

# ===== Network training config ===== #
epochs: 100
weight_decay: 0.00004 
momentum: 0.9
batch_size: 64
T: 4

# ===== Sparsity =========== #
prune_rate: 0.9
conv_type: SparseWeightConv
bn_type: LearnedBatchNorm
init: kaiming_normal
mode: fan_in
nonlinearity: relu
beta: 1

# ===== Hardware setup ===== #
workers: 8